language: csharp
mono: none
os: linux
dist: bionic
dotnet: 3.1
addons:
  apt:
    packages:
    - libc6-dev
    - libgdiplus
script:
# Build
- dotnet build -c release
# Unit tests
- dotnet test -c release
# Integration tests
- cd FilterScript.Test
- ./test-all.sh
- cd ..
# Generate docs
- sudo apt-get update -qq
- sudo apt-get install -qq -y texlive-base texlive-science texlive-xetex texlive-fonts-recommended
  texlive-latex-extra
- sudo apt-get install lmodern
- wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
- sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
- mkdir out
- dotnet FilterScript/bin/Release/netcoreapp3.0/FilterScript.dll --doc > out/doc.md
- pandoc out/doc.md --from=markdown_github-hard_line_breaks+yaml_metadata_block --output=out/doc.html --css=FilterScript/pandoc.css --standalone --self-contained
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out
  token: $GITHUB_TOKEN
  on:
    branch: master
