language: csharp
mono: none
os: linux
dist: bionic
dotnet: 3.1
addons:
  apt:
    packages:
    - libc6-dev
    - libgdiplus
script:
# Build
- dotnet build -c release
# Unit tests
- dotnet test -c release
# Integration tests
- cd FilterScript.Test
- ./test-all.sh
- cd ..
