name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit tests
      run: dotnet test --no-restore --verbosity normal
    - name: Integration tests
      run: cd FilterScript.Test; ./test-all.sh; cd ..
