name: .NET build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-12, windows-latest, windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore NuGet dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit tests
      run: dotnet test --no-restore --verbosity normal
    - name: Integration tests (Ubuntu/Mac)
      if: ${{ startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu') }}
      run: cd FilterScript.Test; ./test-all.sh; cd ..
    - name: Coverage (ubuntu-latest)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io (ubuntu-latest)
      if: ${{ matrix.os == 'ubuntu-latest' }}  
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: FilterLib.Tests/TestResults/coverage.info
